export const ADD_RECIPE_TO_SELECTED_LIST = "ADD_RECIPE_TO_SELECTED_LIST";
export const SELECT_RECIPE = "SELECT_RECIPE";
export const REMOVE_RECIPE_FROM_SELECTED_LIST =
  "REMOVE_RECIPE_FROM_SELECTED_LIST";
export const UPDATE_RECIPE_LIST = "UPDATE_RECIPE_LIST";
export const UPDATE_RECIPE_QUANTITY = "UPDATE_RECIPE_QUANTITY";
